refatorando-usuarios
Brun0Nasc/Frequencias-Backend pull request #3
Opened 2022-09-23 13:56 UTC by Brun0Nasc

refatorando pro padrão sugerido por matheus

2022-09-23 13:58 UTC, caiosousaf approved these changes

2022-09-23 23:20 UTC, matheustgf10 commented on infra/usuarios/postgres/data.go
> +func (pg *DBUsuarios) ListarUsuarios(order int) (res *modelApresentacao.ListaUsuarios, err error) {
Assim ficaria com a sugestão que dei mais cedo, no caso precisaria de duas novas funções nao pacote `utils` e precisaria que na requisição fosse passada os dois parametros pelo query. Ex.: `orderby=nome` e `order=desc`

![codeRequestParamsData](https://user-images.githubusercontent.com/30707765/192068538-2464ae2f-c083-478a-a9b9-a3a0b136c7fb.png)

2022-09-23 23:21 UTC, matheustgf10 commented on infra/usuarios/postgres/data.go
> +func (pg *DBUsuarios) ListarUsuarios(order int) (res *modelApresentacao.ListaUsuarios, err error) {
Com isso teria que ser feita uma refatoração desde o handler.go até o data, pois o parametro deixaria de ser um inteiro e passaria a ser uma estrutura `RequestParams` [também criado no novo arquivo do pacote **utils**].

2022-09-23 23:23 UTC, matheustgf10 commented on infra/usuarios/postgres/data.go
> +func (pg *DBUsuarios) ListarUsuarios(order int) (res *modelApresentacao.ListaUsuarios, err error) {
Assim ficaria o novo arquivo da **utils**. Uma função para percorrer todos os parametros informados na requisição, e uma função do próprio **params**
![codeRequestParamsUtils](https://user-images.githubusercontent.com/30707765/192068771-45c128e2-0392-4972-8c9d-f62d9bc515d3.png)

2022-09-24 16:44 UTC, matheustgf10 requested changes
Tem que fazer as mudanças aqui também se não a build quebra

2022-09-24 16:44 UTC, matheustgf10 commented on infra/usuarios/interface.go
> +	ListarUsuarios(order int) (*modelApresentacao.ListaUsuarios, error)
```suggestion
	ListarUsuarios(params *utils.RequestParams) (*modelApresentacao.ListaUsuarios, error)
```

2022-09-24 16:44 UTC, matheustgf10 commented on domain/usuarios/usecase.go
> +func ListarUsuarios(order int) (res *modelApresentacao.ListaUsuarios, err error) {
```suggestion
func ListarUsuarios(params *utils.RequestParams) (res *modelApresentacao.ListaUsuarios, err error) {
```

2022-09-24 16:45 UTC, matheustgf10 commented on domain/usuarios/usecase.go
> +func ListarUsuarios(order int) (res *modelApresentacao.ListaUsuarios, err error) {
e também no handler.go

2022-09-24 19:46 UTC, matheustgf10 commented
Os problemas relatados acima foram corrigidos na #4.

2022-09-24 19:47 UTC, matheustgf10 approved these changes
A **[FQC-3]** Deve ser mergeada na **[FQC-2]** antes que essa seja mergeada na **main**

2022-09-27 18:11 UTC, matheustgf10 commented
:eyes: tá ficando muito bom, parabéns guys!! :clap: :rocket:

2022-09-28 14:21 UTC, merged